language: android
android:
  components:
    - android-27
    - build-tools-27.1.1

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

before_install:
    - echo yes | sdkmanager "build-tools;27.1.1"

# Run assemble and unit tests
script:
  - ./gradlew clean assembleDebug assembleRelease testDebug
