sudo: false

language: android
components:
    - build-tools-27.1.1
    - android-27
    - sys-img-armeabi-v7a-android-tv-l
    - add-on
    - tools
    - platform-tools

      # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

      # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-17
    - extra
